routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Teams
    Route::delete('teams/destroy', 'TeamController@massDestroy')->name('teams.massDestroy');
    Route::post('teams/media', 'TeamController@storeMedia')->name('teams.storeMedia');
    Route::post('teams/ckmedia', 'TeamController@storeCKEditorImages')->name('teams.storeCKEditorImages');
    Route::resource('teams', 'TeamController');

    // Players
    Route::get('players/matchDetails/{playerid}', 'PlayersController@matchDetails')->name('players.matchDetails');
    Route::delete('players/destroy', 'PlayersController@massDestroy')->name('players.massDestroy');
    Route::post('players/media', 'PlayersController@storeMedia')->name('players.storeMedia');
    Route::post('players/ckmedia', 'PlayersController@storeCKEditorImages')->name('players.storeCKEditorImages');
    Route::resource('players', 'PlayersController');

    // Matches
    Route::get('matches/details/{matchid}', 'MatchController@details')->name('matches.details');
	Route::post('matches/details/update/{matchid}', 'MatchController@detailsUpdate')->name('matches.details.update');
	Route::delete('matches/destroy', 'MatchController@massDestroy')->name('matches.massDestroy');
    Route::resource('matches', 'MatchController');

    // Player Details
    Route::delete('player-details/destroy', 'PlayerDetailsController@massDestroy')->name('player-details.massDestroy');
    Route::resource('player-details', 'PlayerDetailsController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});

resources/views/partials/01-menu.blade.php
<div class="sidebar">
    <nav class="sidebar-nav">

        <ul class="nav">
            <li class="nav-item">
                <a href="{{ route("admin.home") }}" class="nav-link">
                    <i class="nav-icon fas fa-fw fa-tachometer-alt">
                    </i>
                    {{ trans('global.dashboard') }}
                </a>
            </li>
            @can('user_management_access')
                <li class="nav-item nav-dropdown">
                    <a class="nav-link  nav-dropdown-toggle" href="#">
                        <i class="fa-fw fas fa-users nav-icon">

                        </i>
                        {{ trans('cruds.userManagement.title') }}
                    </a>
                    <ul class="nav-dropdown-items">
                        \
						
						
						@can('permission_access')
                            <li class="nav-item">
                                <a href="{{ route("admin.permissions.index") }}" class="nav-link {{ request()->is('admin/permissions') || request()->is('admin/permissions/*') ? 'active' : '' }}">
                                    <i class="fa-fw fas fa-unlock-alt nav-icon"</i>
                                    {{ trans('cruds.permission.title') }}
                                </a>
                            </li>
                        @endcan
                        @can('role_access')
                            <li class="nav-item">
                                <a href="{{ route("admin.roles.index") }}" class="nav-link {{ request()->is('admin/roles') || request()->is('admin/roles/*') ? 'active' : '' }}">
                                    <i data-feather="droplet" class="mr-2"></i>{{ trans('cruds.role.title') }}
                                </a>
                            </li>
                        @endcan
                        @can('user_access')
                            <li class="nav-item">
                                <a href="{{ route("admin.users.index") }}" class="nav-link {{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active' : '' }}">
                                    <i data-feather="droplet" class="mr-2"></i>{{ trans('cruds.user.title') }}
                                </a>
                            </li>
                        @endcan
						
                    </ul>
                </li>
            @endcan

            @can('departments_access')
                <li class="nav-item">
                    <a href="{{ route("admin.departments.index") }}" class="nav-link {{ request()->is('admin/departmentss') || request()->is('admin/departmentss/*') ? 'active' : '' }}">
                        <i class="fa-fw fas fa-cogs nav-icon">

                        </i>
                        {{ trans('cruds.departments.title') }}
                    </a>
                </li>
            @endcan
			
            @can('certificate_access')
                <li class="nav-item">
                    <a href="{{ route("admin.certificates.index") }}" class="nav-link {{ request()->is('admin/certificates') || request()->is('admin/certificates/*') ? 'active' : '' }}">
                        <i class="fa-fw fas fa-cogs nav-icon">

                        </i>
                        {{ trans('cruds.certificate.title') }}
                    </a>
                </li>
            @endcan
			
			
			
			
        <ul class="nav">
			<li class="nav-item nav-dropdown">
				<a class="nav-link  nav-dropdown-toggle" href="#">
					<i class="fa-fw fas fa-users nav-icon"></i>
					{{ trans('global.certificate') }}
				</a>
				<ul class="nav-dropdown-items">
				@can('employee_access')
					<li class="nav-item">
						<a href="{{ route("admin.employees.index") }}" class="nav-link {{ request()->is('admin/employees') || request()->is('admin/employees/*') ? 'active' : '' }}">
							<i class="fa-fw fas fa-cogs nav-icon"></i>
							{{ trans('global.external') }}
						</a>
					</li>
					<li class="nav-item">
						<a href="{{ route("admin.members.index") }}" class="nav-link {{ request()->is('admin/members') || request()->is('admin/members/*') ? 'active' : '' }}">
							<i class="fa-fw fas fa-cogs nav-icon"></i>
							{{ trans('global.members') }}
						</a>
					</li>					
					<li class="nav-item">
						<a href="{{ route("admin.internalemployees.empSearch") }}" class="nav-link {{ request()->is('admin/internalemployees') || request()->is('admin/internalemployees/*') ? 'active' : '' }}">
							<i class="fa-fw fas fa-cogs nav-icon"></i>
							{{ trans('global.internal') }}
						</a>
					</li>
					
				@endcan
				@can('member_access') @endcan

					
					<li class="nav-item d-none1">
						<a href="{{ route("admin.members.all") }}" class="nav-link {{ request()->is('admin/members/all') || request()->is('admin/members/all') ? 'active' : '' }}">
							<i class="fa-fw fas fa-cogs nav-icon"></i>
							{{ trans('global.allmembers') }}
						</a>
					</li>
					<?php /*
					<li class="nav-item">
						<a href="{{ route("admin.employees.listing") }}" class="nav-link {{ request()->is('employees/listing') ? 'active' : '' }}">
							<i class="fa-fw fas fa-cogs nav-icon"></i>
							{{ trans('global.allinternalmembers') }}
						</a>
					</li>*/ ?>
					
					
        @can('internalmember_access')
            <li class="nav-item">
                <a href="{{ route("admin.internalmembers.index") }}" class="nav-link {{ request()->is('admin/internalmembers') || request()->is('admin/internalmembers/*') ? 'active' : '' }}">
                    <i class="fa-fw fas fa-cogs c-sidebar-nav-icon"></i> &nbsp; 
                    {{ trans('cruds.internalmember.title') }}
                </a>
            </li>
        @endcan					
				
				</ul>
            </li>
		</ul>
			
            @if(file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php')))
                @can('profile_password_edit')
                    <li class="nav-item">
                        <a class="nav-link {{ request()->is('profile/password') || request()->is('profile/password/*') ? 'active' : '' }}" href="{{ route('profile.password.edit') }}">
                            <i class="fa-fw fas fa-key nav-icon">
                            </i>
                            {{ trans('global.change_password') }}
                        </a>
                    </li>
                @endcan
            @endif
            <li class="nav-item">
                <a href="#" class="nav-link" onclick="event.preventDefault(); document.getElementById('logoutform').submit();">
                    <i class="nav-icon fas fa-fw fa-sign-out-alt">

                    </i>
                    {{ trans('global.logout') }}
                </a>
            </li>
        </ul>

    </nav>
    <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>

resources/views/partials/02-menu.blade.php
<aside class="left-sidebar">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <li class="mt-3">
                            <a href="{{ route("admin.home") }}" class="btn create-btn text-white no-wrap d-flex align-items-center">
                                <i data-feather="plus"></i>
                                <span class="hide-menu ml-2 text-uppercase">{{ trans('global.dashboard') }}</span>
                            </a>
                        </li>
						@can('user_management_access')
							<li class="sidebar-item">
								<a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)"
									aria-expanded="false">
									<i data-feather="home" class="mr-2"></i>
									<span class="hide-menu">{{ trans('cruds.userManagement.title') }}</span>
								</a>
								<ul aria-expanded="false" class="collapse  first-level">
									
									@can('permission_access')
										<li class="sidebar-item">
											<a href="{{ route("admin.permissions.index") }}" class="sidebar-link {{ request()->is('admin/permissions') || request()->is('admin/permissions/*') ? 'active' : '' }}">
												<i data-feather="droplet" class="mr-2"></i>
												<span class="hide-menu">{{ trans('cruds.permission.title') }}</span>
											</a>
										</li>
									@endcan
									@can('role_access')
										<li class="sidebar-item">
											<a href="{{ route("admin.roles.index") }}" class="sidebar-link {{ request()->is('admin/roles') || request()->is('admin/roles/*') ? 'active' : '' }}">
												<i data-feather="droplet" class="mr-2"></i>
												<span class="hide-menu">{{ trans('cruds.role.title') }}</span>
											</a>
										</li>
									@endcan
									@can('user_access')
										<li class="sidebar-item">
											<a href="{{ route("admin.users.index") }}" class="sidebar-link {{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active' : '' }}">
												<i data-feather="droplet" class="mr-2"></i>
												<span class="hide-menu">{{ trans('cruds.user.title') }}</span>
											</a>
										</li>
									@endcan	
								</ul>
							</li>
						@endcan
						
						
            @can('department_access')
                <li class="sidebar-item">
                    <a href="{{ route("admin.departments.index") }}" class="sidebar-link {{ request()->is('admin/departmentss') || request()->is('admin/departmentss/*') ? 'active' : '' }}">
                        <i data-feather="home" class="mr-2"></i>
                        <span class="hide-menu">{{ trans('cruds.departments.title') }}</span>
                    </a>
                </li>
            @endcan
			
            @can('certificate_access')
                <li class="sidebar-item">
                    <a href="{{ route("admin.certificates.index") }}" class="sidebar-link {{ request()->is('admin/certificates') || request()->is('admin/certificates/*') ? 'active' : '' }}">
                        <i data-feather="home" class="mr-2"></i>
                        <span class="hide-menu">{{ trans('cruds.certificate.title') }}</span>
                    </a>
                </li>
            @endcan						
						
						
						@can('user_management_access')
							<li class="sidebar-item">
								<a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)"
									aria-expanded="false">
									<i data-feather="home" class="mr-2"></i>
									<span class="hide-menu">{{ trans('global.certificate') }}</span>
								</a>
								<ul aria-expanded="false" class="collapse  first-level">
										
									
				@can('employee_access')
					<li class="sidebar-item">
						<a href="{{ route("admin.employees.index") }}" class="sidebar-link {{ request()->is('admin/employees') || request()->is('admin/employees/*') ? 'active' : '' }}">
							<i data-feather="droplet" class="mr-2"></i>
							<span class="hide-menu">{{ trans('global.external') }}</span>
						</a>
					</li>
					<li class="sidebar-item">
						<a href="{{ route("admin.members.index") }}" class="sidebar-link {{ request()->is('admin/members') || request()->is('admin/members/*') ? 'active' : '' }}">
							<i data-feather="droplet" class="mr-2"></i>
							<span class="hide-menu">{{ trans('global.members') }}</span>
						</a>
					</li>					
					<li class="sidebar-item">
						<a href="{{ route("admin.internalemployees.empSearch") }}" class="sidebar-link {{ request()->is('admin/internalemployees') || request()->is('admin/internalemployees/*') ? 'active' : '' }}">
							<i data-feather="droplet" class="mr-2"></i>
							<span class="hide-menu">{{ trans('global.internal') }}</span>
						</a>
					</li>
					
					
					<li class="sidebar-item d-none">
						<a href="{{ route("admin.members.all") }}" class="sidebar-link {{ request()->is('admin/members/all') || request()->is('admin/members/all') ? 'active' : '' }}">
							<i data-feather="droplet" class="mr-2"></i>
							<span class="hide-menu">{{ trans('global.allmembers') }}</span>
						</a>
					</li>
        @can('internalmember_access')
            <li class="sidebar-item">
                <a href="{{ route("admin.internalmembers.index") }}" class="sidebar-link {{ request()->is('admin/internalmembers') || request()->is('admin/internalmembers/*') ? 'active' : '' }}">
                    <i data-feather="droplet" class="mr-2"></i> 
                    <span class="hide-menu">{{ trans('cruds.internalmember.title') }}</span>
                </a>
            </li>
        @endcan						
				@endcan									
									
								</ul>
							</li>
						@endcan
						
            @if(file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php')))
                @can('profile_password_edit')
                    <li class="sidebar-item">
                        <a class="sidebar-link {{ request()->is('profile/password') || request()->is('profile/password/*') ? 'active' : '' }}" href="{{ route('profile.password.edit') }}">
                            <i data-feather="home" class="mr-2"></i>
                            <span class="hide-menu">{{ trans('global.change_password') }}</span>
                        </a>
                    </li>
					<li class="sidebar-item">
						<a  class="sidebar-link" href="javascript:void(0)"  onclick="lgfrm()">
							<i data-feather="home" class="mr-2"></i>
							<span class="hide-menu">{{ trans('global.logout') }}</span>
						</a>
					</li>					
                @endcan
            @endif


			
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>
        

resources/views/partials/menu.blade.php
		<aside class="left-sidebar">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <li class="mt-3">
                            <a href="{{ route("admin.home") }}" class="btn create-btn text-white no-wrap d-flex align-items-center">
                                <i data-feather="plus"></i>
                                <span class="hide-menu ml-2 text-uppercase">{{ trans('global.dashboard') }}</span>
                            </a>
                        </li>
						@can('user_management_access')
							<li class="sidebar-item selected">
								<a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)"
									aria-expanded="false">
									<i data-feather="home" class="mr-2"></i>
									<span class="hide-menu">{{ trans('cruds.userManagement.title') }}</span>
								</a>
								<ul aria-expanded="false" class="collapse  first-level">
									
									@can('permission_access')
										<li class="sidebar-item">
											<a href="{{ route("admin.permissions.index") }}" class="sidebar-link {{ request()->is('admin/permissions') || request()->is('admin/permissions/*') ? 'active' : '' }}">
												<i data-feather="droplet" class="mr-2"></i>
												<span class="hide-menu">{{ trans('cruds.permission.title') }}</span>
											</a>
										</li>
									@endcan
									@can('role_access')
										<li class="sidebar-item">
											<a href="{{ route("admin.roles.index") }}" class="sidebar-link {{ request()->is('admin/roles') || request()->is('admin/roles/*') ? 'active' : '' }}">
												<i data-feather="droplet" class="mr-2"></i>
												<span class="hide-menu">{{ trans('cruds.role.title') }}</span>
											</a>
										</li>
									@endcan
									@can('user_access')
										<li class="sidebar-item">
											<a href="{{ route("admin.users.index") }}" class="sidebar-link {{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active' : '' }}">
												<i data-feather="droplet" class="mr-2"></i>
												<span class="hide-menu">{{ trans('cruds.user.title') }}</span>
											</a>
										</li>
									@endcan	
								</ul>
							</li>
						@endcan

						@can('team_access')
							<li class="sidebar-item selected">
								<a href="{{ route("admin.teams.index") }}" class="sidebar-link {{ request()->is('admin/teams') || request()->is('admin/teams/*') ? 'active' : '' }}">
									<i data-feather="home" class="mr-2"></i>
									{{ trans('cruds.team.title') }}
								</a>
							</li>
						@endcan
						@can('player_access')
							<li class="sidebar-item selected">
								<a href="{{ route("admin.players.index") }}" class="sidebar-link {{ request()->is('admin/players') || request()->is('admin/players/*') ? 'active' : '' }}">
									<i data-feather="home" class="mr-2"></i>
									{{ trans('cruds.player.title') }}
								</a>
							</li>
						@endcan
						@can('match_access')
							<li class="sidebar-item selected">
								<a href="{{ route("admin.matches.index") }}" class="sidebar-link {{ request()->is('admin/matches') || request()->is('admin/matches/*') ? 'active' : '' }}">
									<i data-feather="home" class="mr-2"></i>
									{{ trans('cruds.match.title') }}
								</a>
							</li>
						@endcan
						@if(file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php')))
							@can('profile_password_edit')
								<li class="sidebar-item selected">
									<a class="sidebar-link {{ request()->is('profile/password') || request()->is('profile/password/*') ? 'active' : '' }}" href="{{ route('profile.password.edit') }}">
										<i data-feather="home" class="mr-2"></i>
										{{ trans('global.change_password') }}
									</a>
								</li>
							@endcan
						@endif
						<li class="sidebar-item selected">
							<a href="#" class="sidebar-link" onclick="event.preventDefault(); document.getElementById('logoutform').submit();">
								<i class="c-sidebar-nav-icon fas fa-fw fa-sign-out-alt">

								</i>
								{{ trans('global.logout') }}
							</a>
						</li>
					</ul>
				</nav>
			</div>
		</aside>