routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Teams
    Route::delete('teams/destroy', 'TeamController@massDestroy')->name('teams.massDestroy');
    Route::post('teams/media', 'TeamController@storeMedia')->name('teams.storeMedia');
    Route::post('teams/ckmedia', 'TeamController@storeCKEditorImages')->name('teams.storeCKEditorImages');
    Route::resource('teams', 'TeamController');

    // Players
    Route::get('players/matchDetails/{playerid}', 'PlayersController@matchDetails')->name('players.matchDetails');
    Route::delete('players/destroy', 'PlayersController@massDestroy')->name('players.massDestroy');
    Route::post('players/media', 'PlayersController@storeMedia')->name('players.storeMedia');
    Route::post('players/ckmedia', 'PlayersController@storeCKEditorImages')->name('players.storeCKEditorImages');
    Route::resource('players', 'PlayersController');

    // Matches
    Route::get('matches/details/{matchid}', 'MatchController@details')->name('matches.details');
	Route::post('matches/details/update/{matchid}', 'MatchController@detailsUpdate')->name('matches.details.update');
	Route::delete('matches/destroy', 'MatchController@massDestroy')->name('matches.massDestroy');
    Route::resource('matches', 'MatchController');

    // Player Details
    Route::delete('player-details/destroy', 'PlayerDetailsController@massDestroy')->name('player-details.massDestroy');
    Route::resource('player-details', 'PlayerDetailsController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});

app/Match.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;

class Match extends Model
{
    use SoftDeletes;

    public $table = 'matches';

    protected $dates = [
        'match_date',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'team_one',
        'team_two',
        'winner',
        'match_date',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function getMatchDateAttribute($value)
    {
        return $value ? Carbon::createFromFormat('Y-m-d H:i:s', $value)->format(config('panel.date_format') . ' ' . config('panel.time_format')) : null;
    }

    public function setMatchDateAttribute($value)
    {
        $this->attributes['match_date'] = $value ? Carbon::createFromFormat(config('panel.date_format') . ' ' . config('panel.time_format'), $value)->format('Y-m-d H:i:s') : null;
    }
	
    public function teamsOne()
    {
    	return $this->belongsTo('App\Team','team_one');
    }	
		
    public function teamsTwo()
    {
    	return $this->belongsTo('App\Team','team_two');
    }	
	    
	public function winnerTeam()
    {
    	return $this->belongsTo('App\Team','winner');
    }	
		
	
}

app/Http/Controllers/Admin/MatchController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyMatchRequest;
use App\Http\Requests\StoreMatchRequest;
use App\Http\Requests\UpdateMatchRequest;
use App\Match;
use App\MatchDetail;
use App\PlayerDetail;
use App\Team;
use App\Player;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class MatchController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('match_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $matches = Match::all();

        return view('admin.matches.index', compact('matches'));
    }

    public function create()
    {
        abort_if(Gate::denies('match_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');
		$data['teamlist'] = Team::get()->toArray();
		$data['playerlist'] = Player::get()->toArray();
		//dd($teams);
        return view('admin.matches.create', compact('data'));
    }

    public function store(StoreMatchRequest $request)
    {
        $addDetails = $request->addDetails;
		$team_one = $request->team_one;
		$team_two = $request->team_two;
		$winner = $request->winner;
		
		if($team_one == $team_two){
			return  back()->with('error','Both team can\'t be same.');;
		}
		
		if(!in_array($winner,array(0,$team_one,$team_two))){
			return  back()->with('error','Winner can\'t be other team.');;
		}		
		
		
		
		$match = Match::create($request->all());
		
		if($addDetails){
			return redirect()->route('admin.matches.details', $match->id);
		}
		else{
			return redirect()->route('admin.matches.index');
		}		
    }

    public function edit(Match $match)
    {
        abort_if(Gate::denies('match_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');
		$data['match_details'] 	= MatchDetail::where('match',$match->id)->get()->count();		
		$data['teamlist'] 		= Team::get()->toArray();
		
		$data['playerlist'] = Player::get()->toArray();
		//dd($teams);
        return view('admin.matches.edit', compact('match','data'));
    }

    public function update(UpdateMatchRequest $request, Match $match)
    {
		$team_one = $request->team_one;
		$team_two = $request->team_two;
		$winner = $request->winner;		
		if($team_one == $team_two){
			return  back()->with('error','Both team can\'t be same.');;
		}	

		if(!in_array($winner,array(0,$team_one,$team_two))){
			return  back()->with('error','Winner can\'t be other team.');;
		}
		
        $match->update($request->all());
        return redirect()->route('admin.matches.index');
    }

    public function show(Match $match)
    {
        abort_if(Gate::denies('match_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.matches.show', compact('match'));
    }

    public function destroy(Match $match)
    {
        abort_if(Gate::denies('match_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $match->delete();

        return back();
    }

    public function massDestroy(MassDestroyMatchRequest $request)
    {
        Match::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
	
	public function details($matchid){		
		$match 				= Match::where('id',$matchid)->get();		
		foreach($match as $val){
			$teamsOne = $val->teamsOne->name;
			$teamsTwo = $val->teamsTwo->name;
		}

		$match_details 		= MatchDetail::where('match',$matchid)->get()->toArray();
		$playerlist 		= Player::get()->toArray();		
		
		return view('admin.matches.details', compact('match','match_details','playerlist','teamsOne','teamsTwo'));
	}
	
	public function detailsUpdate(Request $request,$matchid){
		$matchDetails 	= $request->matchDetails;
		$playerids = array();
		foreach($matchDetails as $val){
			if(in_array($val['player'],$playerids)){
				return  back()->with('error','Duplicate player not allow.');;
			}
			$playerids[] = $val['player'];
		}
		
		//dd($playerids,$matchDetails);
		
		$type 			= $request->type; 
		if($type == 0){
			foreach($matchDetails as $val){
				$val['match'] = $matchid;
				MatchDetail::insert($val);
			}			
		}
		else{
			foreach($matchDetails as $val){
				$mdid = $val['id'];
				unset($val['id']);
				$val['match'] = $matchid;
				MatchDetail::where('id',$mdid)->update($val);
			}			
		}
		return  back()->with('success','Match details updated successfully.');;
	}
}

resources/views/admin/matches/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.match.title_singular') }}
    </div>

    <div class="card-body">
		@if ($message = Session::get('error'))
			<div class="alert alert-danger">
				<p>{{ $message }}</p>
			</div>
		@endif	
	
        <form method="POST" action="{{ route("admin.matches.store") }}" enctype="multipart/form-data">
            @csrf
			<input type="hidden" name="addDetails" id="addDetails" value="0" /> 
			<div class="row">			
				<div class="col-md-3 col-sm-6">				
					<div class="form-group">
						<label class="required" for="team_one">{{ trans('cruds.match.fields.team_one') }}</label>
						<select name="team_one" id="team_one" class="form-control">
							@foreach($data['teamlist'] as $val)
								<option value="{{$val['id']}}" @if($val['id'] == old('team_one', '0')) selected @endif>{{$val['name']}}</option>
							@endforeach
						</select>                
						@if($errors->has('team_one'))
							<div class="invalid-feedback">
								{{ $errors->first('team_one') }}
							</div>
						@endif
						<span class="help-block">{{ trans('cruds.match.fields.team_one_helper') }}</span>
					</div>
				</div>					
				<div class="col-md-3 col-sm-6">
			
					<div class="form-group">
						<label class="required" for="team_two">{{ trans('cruds.match.fields.team_two') }}</label>
						<select name="team_two" id="team_two" class="form-control">
							@foreach($data['teamlist'] as $val)
								<option value="{{$val['id']}}" @if($val['id'] == old('team_two', '0')) selected @endif>{{$val['name']}}</option>
							@endforeach
						</select>                
						@if($errors->has('team_two'))
							<div class="invalid-feedback">
								{{ $errors->first('team_two') }}
							</div>
						@endif
						<span class="help-block">{{ trans('cruds.match.fields.team_two_helper') }}</span>
					</div>
				</div>
				<div class="col-md-3 col-sm-6">			
					<div class="form-group">
						<label class="required" for="match_date">{{ trans('cruds.match.fields.match_date') }}</label>
						<input class="form-control datetime {{ $errors->has('match_date') ? 'is-invalid' : '' }}" type="text" name="match_date" id="match_date" value="{{ old('match_date') }}" required>
						@if($errors->has('match_date'))
							<div class="invalid-feedback">
								{{ $errors->first('match_date') }}
							</div>
						@endif
						<span class="help-block">{{ trans('cruds.match.fields.match_date_helper') }}</span>
					</div>
				</div>	 			
				<div class="col-md-3 col-sm-6">			
					<div class="form-group">
						<label class="" for="winner">{{ trans('cruds.match.fields.winner') }}</label>
						<select name="winner" id="winner" class="form-control">					
							<option value="0">N/A</option>
							@foreach($data['teamlist'] as $val)
								<option value="{{$val['id']}}" @if($val['id'] == old('winner', '0')) selected @endif>{{$val['name']}}</option>
							@endforeach
						</select>                
						@if($errors->has('winner'))
							<div class="invalid-feedback">
								{{ $errors->first('winner') }}
							</div>
						@endif
						<span class="help-block">{{ trans('cruds.match.fields.winner_helper') }}</span>
					</div>
				</div>										
			</div>
			<div class="row">			
				<div class="col-md-3 col-sm-6">
			
					<div class="form-group">
						<button class="btn btn-danger" type="submit" id="sbmt">
							{{ trans('global.save') }}
						</button>
						<button class="btn btn-info" type="button" onclick="addMatchDetails()">
							{{ trans('global.add_details') }}
						</button>					
					</div>
				</div>			
			</div>
        </form>
    </div>
</div>
@endsection

@section('scripts')
 <script>
addMatchDetails = function(){
	$('#addDetails').val(1);
	$('#sbmt').click();
}
</script>  
@endsection

resources/views/admin/matches/details.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.match_details') }} on {{date('d-m-Y H:i',strtotime($match[0]->match_date))}}
    </div>

    <div class="card-body">
		@if ($message = Session::get('success'))
			<div class="alert alert-success">
				<p>{{ $message }}</p>
			</div>
		@endif
		@if ($message = Session::get('error'))
			<div class="alert alert-danger">
				<p>{{ $message }}</p>
			</div>
		@endif			
		
        <form method="POST" action="{{ route("admin.matches.details.update", [$match[0]->id]) }}" enctype="multipart/form-data">
            @method('POST')
            @csrf
			<input type="hidden" name="type" value="{{count($match_details)}}" />
			<div class="row">	
				<?php 
					$j = 0;
					$k = -1;
					while($j<2){ 
						$j++;
						$team_id = 0;
						if($j == 1){
							$team_id = $match[0]->team_one;
						}
						elseif($j == 2){
							$team_id = $match[0]->team_two;
						}
				?> 
				<div class="col-lg-6 col-md-6">	
					
						<div class="card-header">
							@if($j == 1){{ $teamsOne }}@else{{ $teamsTwo }}@endif
						</div>
					<div  style="border:1px solid #b9883b; padding:10px; margin-bottom:10px;">	
			<?php 
				$i = 0;
				while($i<config('data.playerno'))
				{
					$i++;
					$k++;
			?>
			
			@if(isset($match_details[$k]['id']))
				@php($match_details_id = $match_details[$k]['id'])
			@else
				@php($match_details_id = 0)
			@endif
			<div class="row">			
				<div class="col-md-6">			
					<div class="form-group">
						<input type="hidden" name="matchDetails[{{$k}}][id]" value="{{$match_details_id}}" />
						<input type="hidden" name="matchDetails[{{$k}}][team]" value="{{$team_id}}" />
						<select name="matchDetails[{{$k}}][player]" id="team_one" class="form-control">
							@foreach($playerlist as $val)
								<option value="{{$val['id']}}" @if(isset($match_details[$k]['player']) && $match_details[$k]['player'] ==  $val['id']) selected @endif >{{$val['first_name'].' '.$val['last_name']}}</option>
							@endforeach
						</select>                
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<input type="text" name="matchDetails[{{$k}}][run]" value="@if(isset($match_details[$k]['run'])){{$match_details[$k]['run']}}@else{{0}}@endif" class="form-control">               
					</div>
				</div>				
			</div>
			<?php } ?>

					</div>
				</div>
				<?php } ?>
				
			</div>
			
			<div class="row">
				<div class="col-md-12">
					<div class="form-group">
						<button class="btn btn-danger" type="submit">
							{{ trans('global.save') }}
						</button>

					</div>
				</div>
			</div>
		</form>	

			<div class="clear" ></div>

        
    </div>
</div>



@endsection

resources/views/admin/matches/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.match.title_singular') }}
    </div>

    <div class="card-body">
		@if ($message = Session::get('error'))
			<div class="alert alert-danger">
				<p>{{ $message }}</p>
			</div>
		@endif	
	
        <form method="POST" action="{{ route("admin.matches.update", [$match->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf			
			<div class="row">			
				<div class="col-md-3 col-sm-6">			
					<div class="form-group">
						<label class="required" for="team_one">{{ trans('cruds.match.fields.team_one') }}</label>
						<select name="team_one" id="team_one" class="form-control" @if($data['match_details'] != 0) disabled @endif>
							@foreach($data['teamlist'] as $val)
								<option value="{{$val['id']}}" @if($val['id'] == $match->team_one) selected @endif>{{$val['name']}}</option>
							@endforeach
						</select>                
						@if($errors->has('team_one'))
							<div class="invalid-feedback">
								{{ $errors->first('team_one') }}
							</div>
						@endif
						<span class="help-block">{{ trans('cruds.match.fields.team_one_helper') }}</span>
					</div>
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="form-group">
						<label class="required" for="team_two">{{ trans('cruds.match.fields.team_two') }}</label>
						<select name="team_two" id="team_two" class="form-control" @if($data['match_details'] != 0) disabled @endif>
							@foreach($data['teamlist'] as $val)
								<option value="{{$val['id']}}" @if($val['id'] == $match->team_two) selected @endif>{{$val['name']}}</option>
							@endforeach
						</select>                
						@if($errors->has('team_two'))
							<div class="invalid-feedback">
								{{ $errors->first('team_two') }}
							</div>
						@endif
						<span class="help-block">{{ trans('cruds.match.fields.team_two_helper') }}</span>
					</div>
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="form-group">
						<label class="required" for="match_date">{{ trans('cruds.match.fields.match_date') }}</label>
						<input class="form-control datetime {{ $errors->has('match_date') ? 'is-invalid' : '' }}" type="text" name="match_date" id="match_date" value="{{ old('match_date', $match->match_date) }}" required>
						@if($errors->has('match_date'))
							<div class="invalid-feedback">
								{{ $errors->first('match_date') }}
							</div>
						@endif
						<span class="help-block">{{ trans('cruds.match.fields.match_date_helper') }}</span>
					</div>
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="form-group">
						<label class="" for="winner">{{ trans('cruds.match.fields.winner') }}</label>
						<select name="winner" id="winner" class="form-control">					
							<option value="0">N/A</option>
							@foreach($data['teamlist'] as $val)
								<option value="{{$val['id']}}" @if($val['id'] == $match->winner) selected @endif>{{$val['name']}}</option>
							@endforeach
						</select>                
						@if($errors->has('winner'))
							<div class="invalid-feedback">
								{{ $errors->first('winner') }}
							</div>
						@endif
						<span class="help-block">{{ trans('cruds.match.fields.winner_helper') }}</span>
					</div>
				</div>
				
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="form-group">
						<button class="btn btn-danger" type="submit">
							{{ trans('global.save') }}
						</button>
						@if($data['match_details'] == 0)
							<a href="{{ route('admin.matches.details', $match->id) }}" class="btn btn-info" >
								{{ trans('global.add_details') }}
							</a>
						@else
							<a href="{{ route('admin.matches.details', $match->id) }}" class="btn btn-info" >
								{{ trans('global.update_details') }}
							</a>
						@endif
					</div>
				</div>
			</div>
			
			
			<div class="clear" ></div>

        </form>
    </div>
</div>



@endsection

resources/views/admin/matches/index.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('cruds.match.title_singular') }} {{ trans('global.list') }}
@can('match_create')
	<a class="btn btn-success btn-sm float-right" href="{{ route('admin.matches.create') }}">
		{{ trans('global.add') }} {{ trans('cruds.match.title_singular') }}
	</a>
@endcan		
    </div>

    <div class="card-body">
	
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Match">
                <thead>
                    <tr>
                        <th>
                            {{ trans('cruds.match.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.match.fields.team_one') }}
                        </th>
                        <th>
                            {{ trans('cruds.match.fields.team_two') }}
                        </th>
                        <th>
                            {{ trans('cruds.match.fields.winner') }}
                        </th>
                        <th>
                            {{ trans('cruds.match.fields.match_date') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($matches as $key => $match)
                        <tr data-entry-id="{{ $match->id }}">
                            <td>
                                {{ $match->id ?? '' }}
                            </td>
                            <td>
								{{ $match->teamsOne->name }}
                            </td>
                            <td>
                                {{ $match->teamsTwo->name ?? '' }}
                            </td>
                            <td>
                                {{ $match->winnerTeam->name ?? 'N/A' }}
                            </td>
                            <td>
                                {{ $match->match_date ?? '' }}
                            </td>
                            <td>
                                @can('match_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.matches.show', $match->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('match_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.matches.edit', $match->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('match_delete')
                                    <form action="{{ route('admin.matches.destroy', $match->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('match_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.matches.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Match:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/matches/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.match.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.matches.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.match.fields.id') }}
                        </th>
                        <td>
                            {{ $match->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.match.fields.team_one') }}
                        </th>
                        <td>
                            {{ $match->team_one }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.match.fields.team_two') }}
                        </th>
                        <td>
                            {{ $match->team_two }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.match.fields.winner') }}
                        </th>
                        <td>
                            {{ $match->winner }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.match.fields.match_date') }}
                        </th>
                        <td>
                            {{ $match->match_date }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.matches.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection