routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Teams
    Route::delete('teams/destroy', 'TeamController@massDestroy')->name('teams.massDestroy');
    Route::post('teams/media', 'TeamController@storeMedia')->name('teams.storeMedia');
    Route::post('teams/ckmedia', 'TeamController@storeCKEditorImages')->name('teams.storeCKEditorImages');
    Route::resource('teams', 'TeamController');

    // Players
    Route::get('players/matchDetails/{playerid}', 'PlayersController@matchDetails')->name('players.matchDetails');
    Route::delete('players/destroy', 'PlayersController@massDestroy')->name('players.massDestroy');
    Route::post('players/media', 'PlayersController@storeMedia')->name('players.storeMedia');
    Route::post('players/ckmedia', 'PlayersController@storeCKEditorImages')->name('players.storeCKEditorImages');
    Route::resource('players', 'PlayersController');

    // Matches
    Route::get('matches/details/{matchid}', 'MatchController@details')->name('matches.details');
	Route::post('matches/details/update/{matchid}', 'MatchController@detailsUpdate')->name('matches.details.update');
	Route::delete('matches/destroy', 'MatchController@massDestroy')->name('matches.massDestroy');
    Route::resource('matches', 'MatchController');

    // Player Details
    Route::delete('player-details/destroy', 'PlayerDetailsController@massDestroy')->name('player-details.massDestroy');
    Route::resource('player-details', 'PlayerDetailsController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});

app/PlayerDetail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;

class PlayerDetail extends Model
{
    use SoftDeletes;

    public $table = 'player_details';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'player',
        'match',
        'team',
        'run',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/PlayerDetailsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyPlayerDetailRequest;
use App\Http\Requests\StorePlayerDetailRequest;
use App\Http\Requests\UpdatePlayerDetailRequest;
use App\PlayerDetail;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class PlayerDetailsController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('player_detail_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $playerDetails = PlayerDetail::all();

        return view('admin.playerDetails.index', compact('playerDetails'));
    }

    public function create()
    {
        abort_if(Gate::denies('player_detail_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.playerDetails.create');
    }

    public function store(StorePlayerDetailRequest $request)
    {
        $playerDetail = PlayerDetail::create($request->all());

        return redirect()->route('admin.player-details.index');
    }

    public function edit(PlayerDetail $playerDetail)
    {
        abort_if(Gate::denies('player_detail_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.playerDetails.edit', compact('playerDetail'));
    }

    public function update(UpdatePlayerDetailRequest $request, PlayerDetail $playerDetail)
    {
        $playerDetail->update($request->all());

        return redirect()->route('admin.player-details.index');
    }

    public function show(PlayerDetail $playerDetail)
    {
        abort_if(Gate::denies('player_detail_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.playerDetails.show', compact('playerDetail'));
    }

    public function destroy(PlayerDetail $playerDetail)
    {
        abort_if(Gate::denies('player_detail_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $playerDetail->delete();

        return back();
    }

    public function massDestroy(MassDestroyPlayerDetailRequest $request)
    {
        PlayerDetail::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/playerDetails/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.playerDetail.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.player-details.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="player">{{ trans('cruds.playerDetail.fields.player') }}</label>
                <input class="form-control {{ $errors->has('player') ? 'is-invalid' : '' }}" type="number" name="player" id="player" value="{{ old('player', '0') }}" step="1" required>
                @if($errors->has('player'))
                    <div class="invalid-feedback">
                        {{ $errors->first('player') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.playerDetail.fields.player_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="match">{{ trans('cruds.playerDetail.fields.match') }}</label>
                <input class="form-control {{ $errors->has('match') ? 'is-invalid' : '' }}" type="number" name="match" id="match" value="{{ old('match', '0') }}" step="1" required>
                @if($errors->has('match'))
                    <div class="invalid-feedback">
                        {{ $errors->first('match') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.playerDetail.fields.match_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="team">{{ trans('cruds.playerDetail.fields.team') }}</label>
                <input class="form-control {{ $errors->has('team') ? 'is-invalid' : '' }}" type="number" name="team" id="team" value="{{ old('team', '0') }}" step="1" required>
                @if($errors->has('team'))
                    <div class="invalid-feedback">
                        {{ $errors->first('team') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.playerDetail.fields.team_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="run">{{ trans('cruds.playerDetail.fields.run') }}</label>
                <input class="form-control {{ $errors->has('run') ? 'is-invalid' : '' }}" type="number" name="run" id="run" value="{{ old('run', '0') }}" step="1" required>
                @if($errors->has('run'))
                    <div class="invalid-feedback">
                        {{ $errors->first('run') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.playerDetail.fields.run_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/playerDetails/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.playerDetail.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.player-details.update", [$playerDetail->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="player">{{ trans('cruds.playerDetail.fields.player') }}</label>
                <input class="form-control {{ $errors->has('player') ? 'is-invalid' : '' }}" type="number" name="player" id="player" value="{{ old('player', $playerDetail->player) }}" step="1" required>
                @if($errors->has('player'))
                    <div class="invalid-feedback">
                        {{ $errors->first('player') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.playerDetail.fields.player_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="match">{{ trans('cruds.playerDetail.fields.match') }}</label>
                <input class="form-control {{ $errors->has('match') ? 'is-invalid' : '' }}" type="number" name="match" id="match" value="{{ old('match', $playerDetail->match) }}" step="1" required>
                @if($errors->has('match'))
                    <div class="invalid-feedback">
                        {{ $errors->first('match') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.playerDetail.fields.match_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="team">{{ trans('cruds.playerDetail.fields.team') }}</label>
                <input class="form-control {{ $errors->has('team') ? 'is-invalid' : '' }}" type="number" name="team" id="team" value="{{ old('team', $playerDetail->team) }}" step="1" required>
                @if($errors->has('team'))
                    <div class="invalid-feedback">
                        {{ $errors->first('team') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.playerDetail.fields.team_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="run">{{ trans('cruds.playerDetail.fields.run') }}</label>
                <input class="form-control {{ $errors->has('run') ? 'is-invalid' : '' }}" type="number" name="run" id="run" value="{{ old('run', $playerDetail->run) }}" step="1" required>
                @if($errors->has('run'))
                    <div class="invalid-feedback">
                        {{ $errors->first('run') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.playerDetail.fields.run_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/playerDetails/index.blade.php
@extends('layouts.admin')
@section('content')
@can('player_detail_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.player-details.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.playerDetail.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.playerDetail.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-PlayerDetail">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.playerDetail.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.playerDetail.fields.player') }}
                        </th>
                        <th>
                            {{ trans('cruds.playerDetail.fields.match') }}
                        </th>
                        <th>
                            {{ trans('cruds.playerDetail.fields.team') }}
                        </th>
                        <th>
                            {{ trans('cruds.playerDetail.fields.run') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($playerDetails as $key => $playerDetail)
                        <tr data-entry-id="{{ $playerDetail->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $playerDetail->id ?? '' }}
                            </td>
                            <td>
                                {{ $playerDetail->player ?? '' }}
                            </td>
                            <td>
                                {{ $playerDetail->match ?? '' }}
                            </td>
                            <td>
                                {{ $playerDetail->team ?? '' }}
                            </td>
                            <td>
                                {{ $playerDetail->run ?? '' }}
                            </td>
                            <td>
                                @can('player_detail_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.player-details.show', $playerDetail->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('player_detail_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.player-details.edit', $playerDetail->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('player_detail_delete')
                                    <form action="{{ route('admin.player-details.destroy', $playerDetail->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('player_detail_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.player-details.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-PlayerDetail:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/playerDetails/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.playerDetail.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.player-details.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.playerDetail.fields.id') }}
                        </th>
                        <td>
                            {{ $playerDetail->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.playerDetail.fields.player') }}
                        </th>
                        <td>
                            {{ $playerDetail->player }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.playerDetail.fields.match') }}
                        </th>
                        <td>
                            {{ $playerDetail->match }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.playerDetail.fields.team') }}
                        </th>
                        <td>
                            {{ $playerDetail->team }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.playerDetail.fields.run') }}
                        </th>
                        <td>
                            {{ $playerDetail->run }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.player-details.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection